---
- hosts: 127.0.0.1
  tasks:
      - name: create an empty log file on my local machine and run it with maven project
        file:
             path: /root/ansible/log/monitor.log
             state: touch
- hosts: local
  become: yes
  tasks:
      - name: create user
        user:
             name: tiru_ansible
             password: 'release'
             state: present
             shell: /bin/bash
