---
# Adding Multiple users
# I have configured Jenkins with Github successfully
- hosts: local
  become: yes 
  become_user: root

  tasks:
  - include_vars: users.yml
  - name: Creating users to Jump Server
    user: name="{{ item.username}}"
    with_items: "{{ users }}"
